kind: pipeline
type: docker
name: default

steps:
- name: download assets
  image: node:12-alpine
  commands:
  - export npm_config_cache="$PWD/node_cache"
  - |
    for dir in assets_src/*/; do
      dir="$${dir%/}"
      [ -f "$dir/package.json" ] || { echo ".. skip $dir" ; continue; }
      echo ">> Building and installing assets package $${dir##*/}"
      ( cd "$dir" && npm install --unsafe-perm )
    done
- name: compile sass
  image: apluslms/develop-sass:1
  commands:
  - sass --style=compressed assets/sass:assets/css
