inherits:
  - default
ignore-paths:
  - venv
  - aplus/local_settings.py
  - aplus/local_settings.example.py
  - aplus/local_settings.test.py
  - aplus/secret_key.py
  - e2e_tests/assets
  - src/drf-extensions
ignore-patterns:
  - ^.*\/migrations\/.*$

pycodestyle:
  disable:
    - E722
  options:
    max-line-length: 119

pylint:
  enable:
    - trailing-whitespace
  disable:
    - consider-using-f-string
    - import-error
    - protected-access
    - django-not-configured
    - relative-beyond-top-level
    - cyclic-import
    - imported-auth-user
    - too-many-positional-arguments
  options:
    jobs: 0

pyflakes:
  run: false
