# Generated by Django 3.2.4 on 2021-08-12 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0051_auto_20210812_1536'),
        ('news', '0003_alter_news_audience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['course_instance', '-pin', '-publish'], 'verbose_name': 'MODEL_NAME_NEWS', 'verbose_name_plural': 'MODEL_NAME_NEWS_PLURAL'},
        ),
        migrations.AlterField(
            model_name='news',
            name='audience',
            field=models.IntegerField(choices=[(1, 'INTERNAL_USERS'), (2, 'EXTERNAL_USERS'), (3, 'ALL_USERS')], default=3, verbose_name='LABEL_AUDIENCE'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='LABEL_BODY'),
        ),
        migrations.AlterField(
            model_name='news',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='course.courseinstance', verbose_name='LABEL_COURSE_INSTANCE'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='LABEL_PIN'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='LABEL_PUBLISH'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='LABEL_TITLE'),
        ),
    ]
