# Generated by Django 4.2.11 on 2024-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_auto_20210812_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="language",
            field=models.CharField(
                choices=[
                    ("-", "All"),
                    ("en", "English"),
                    ("fi", "Finnish"),
                    ("sv", "Swedish"),
                ],
                default="-",
                max_length=30,
                verbose_name="LANGUAGE",
            ),
        ),
    ]
