# Generated by Django 3.2.4 on 2021-08-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210812_1536'),
        ('exercise', '0039_auto_20210812_1536'),
        ('deviations', '0002_deadlineruledeviation_without_late_penalty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlineruledeviation',
            options={'verbose_name': 'MODEL_NAME_DEADLINE_RULE_DEVIATION', 'verbose_name_plural': 'MODEL_NAME_DEADLINE_RULE_DEVIATION_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='maxsubmissionsruledeviation',
            options={'verbose_name': 'MODEL_NAME_MAX_SUBMISSIONS_RULE_DEVIATION', 'verbose_name_plural': 'MODEL_NAME_MAX_SUBMISSIONS_RULE_DEVIATION_PLURAL'},
        ),
        migrations.AlterField(
            model_name='deadlineruledeviation',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AlterField(
            model_name='deadlineruledeviation',
            name='extra_minutes',
            field=models.IntegerField(verbose_name='LABEL_EXTRA_MINUTES'),
        ),
        migrations.AlterField(
            model_name='deadlineruledeviation',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='LABEL_SUBMITTER'),
        ),
        migrations.AlterField(
            model_name='deadlineruledeviation',
            name='without_late_penalty',
            field=models.BooleanField(default=True, verbose_name='LABEL_WITHOUT_LATE_PENALTY'),
        ),
        migrations.AlterField(
            model_name='maxsubmissionsruledeviation',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AlterField(
            model_name='maxsubmissionsruledeviation',
            name='extra_submissions',
            field=models.IntegerField(verbose_name='LABEL_EXTRA_SUBMISSIONS'),
        ),
        migrations.AlterField(
            model_name='maxsubmissionsruledeviation',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='LABEL_SUBMITTER'),
        ),
    ]
