# Generated by Django 3.2.4 on 2021-12-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210812_1536'),
        ('deviations', '0003_auto_20210812_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlineruledeviation',
            name='grant_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='LABEL_GRANT_TIME'),
        ),
        migrations.AddField(
            model_name='deadlineruledeviation',
            name='granter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='userprofile.userprofile', verbose_name='LABEL_GRANTER'),
        ),
        migrations.AddField(
            model_name='maxsubmissionsruledeviation',
            name='grant_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='LABEL_GRANT_TIME'),
        ),
        migrations.AddField(
            model_name='maxsubmissionsruledeviation',
            name='granter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='userprofile.userprofile', verbose_name='LABEL_GRANTER'),
        ),
    ]
