# Generated by Django 3.2.4 on 2022-02-11 13:40

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0045_auto_20220211_1540'),
        ('deviations', '0004_auto_20211207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlineruledeviation',
            name='exercise',
            field=lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AlterField(
            model_name='maxsubmissionsruledeviation',
            name='exercise',
            field=lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
    ]
