# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_auto_20170609_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
