# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_courseinstance_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
