# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_auto_20180607_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='anon_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
