# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-27 11:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_auto_20180920_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this course.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$', 32))]),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this course instance.', max_length=255, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$', 32))]),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this module.', max_length=255, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$', 32))]),
        ),
    ]
