# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_auto_20190327_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='view_content_to',
            field=models.IntegerField(choices=[(1, 'Enrolled students'), (2, 'Enrollment audience'), (3, 'All registered users'), (4, 'Public to internet')], default=1),
        ),
    ]
