# Generated by Django 2.2.3 on 2019-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_hardcodedusertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='reading_opening_time',
            field=models.DateTimeField(blank=True, help_text='Leave empty if the reading material should not open before the exercises.', null=True, verbose_name='Opening time for the reading material'),
        ),
    ]
