# Generated by Django 2.2.3 on 2020-01-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_hardcodedusertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='status',
            field=models.CharField(choices=[('exam', 'Exam'), ('hidden', 'Hidden'), ('maintenance', 'Maintenance'), ('ready', 'Ready'), ('unlisted', 'Unlisted in table of contents')], default='ready', max_length=32),
        ),
    ]
