# Generated by Django 2.2.13 on 2020-06-26 07:55

from django.db import migrations
from django.db.models import Count, Min
from course.models import Enrollment


def delete_duplicates(apps, schema_editor):

    unique_fields = ['course_instance', 'user_profile']

    duplicates = (
        Enrollment.objects
            .values(*unique_fields)
            .order_by()
            .annotate(min_id=Min('id'), count_id=Count('id'))
            .filter(count_id__gt=1)
    )

    for duplicate in duplicates:
        (
            Enrollment.objects
                .filter(**{x: duplicate[x] for x in unique_fields})
                .exclude(id=duplicate['min_id'])
                .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200721_1422'),
        ('course', '0047_enrollment_language'),
    ]

    operations = [
        migrations.RunPython(delete_duplicates),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('course_instance', 'user_profile')]),
        ),
    ]
