# Generated by Django 3.2.7 on 2021-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0052_courseinstance_sis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='from_sis',
            field=models.BooleanField(default=False, verbose_name='LABEL_FROM_SIS'),
        ),
    ]
