# Generated by Django 3.2.7 on 2021-12-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0053_enrollment_from_sis'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='sis_enroll',
            field=models.BooleanField(default=False, help_text='COURSE_INSTANCE_SIS_ENROLL_HELP', verbose_name='LABEL_SIS_ENROLL'),
        ),
    ]
