# Generated by Django 3.2.12 on 2022-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0054_courseinstance_sis_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'REMOVED'), (3, 'BANNED'), (4, 'PENDING')], default=1, verbose_name='LABEL_STATUS'),
        ),
    ]
