# Generated by Django 4.2.3 on 2023-07-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0056_enrollment_time_help_text'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usertagging',
            new_name='course_user_user_id_b32e3d_idx',
            old_fields=('user', 'course_instance'),
        ),
    ]
