# Generated by Django 4.2.4 on 2023-08-29 13:50

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0048_alter_revealrule_trigger'),
        ('course', '0057_usertagging_rename_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='model_answer',
            field=lib.fields.DefaultForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_answer_modules', to='exercise.coursechapter', verbose_name='LABEL_MODEL_ANSWER'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='model_solution_reveal_rule',
            field=lib.fields.DefaultOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercise.revealrule', verbose_name='LABEL_MODEL_SOLUTION_REVEAL_RULE'),
        ),
    ]
