# Generated by Django 4.2.13 on 2024-05-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0058_coursemodule_model_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinstance",
            name="group_work_allowed",
            field=models.BooleanField(
                default=True, verbose_name="LABEL_GROUP_WORK_ALLOWED"
            ),
        ),
    ]
