# Generated by Django 4.2.11 on 2024-04-30 12:49

import colorfield
from django.db import migrations, models
import django.db.models.deletion
import lib.models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0058_coursemodule_model_answer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for tag", max_length=20),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug key for tag. If left blank, one is created from name",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Describe the usage or meaning of this tag",
                        max_length=155,
                    ),
                ),
                (
                    "color",
                    colorfield.ColorField(
                        default="#CD0000",
                        help_text="Color that is used as background for this tag",
                        max_length=7,
                    ),
                ),
                (
                    "visible_to_students",
                    models.BooleanField(
                        default=False, verbose_name="LABEL_VISIBLE_TO_STUDENTS"
                    ),
                ),
                (
                    "course_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissiontags",
                        to="course.courseinstance",
                        verbose_name="LABEL_COURSE_INSTANCE",
                    ),
                ),
            ],
            options={
                "verbose_name": "MODEL_NAME_SUBMISSION_TAG",
                "verbose_name_plural": "MODEL_NAME_SUBMISSION_TAG_PLURAL",
                "ordering": ["id"],
            },
            bases=(lib.models.UrlMixin, models.Model),
        ),
    ]
