# Generated by Django 4.2.11 on 2024-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0059_submissiontag"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemodule",
            name="personalized_points_goal",
            field=models.PositiveIntegerField(
                default=100, verbose_name="LABEL_PERSONALIZED_POINTS_GOAL"
            ),
        ),
    ]
