# Generated by Django 4.2.11 on 2024-06-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0060_coursemodule_personalized_points_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursemodule",
            name="personalized_points_goal",
        ),
    ]
