# Generated by Django 4.2.11 on 2024-09-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0060_studentmodulegoal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmodulegoal",
            name="goal_percentage",
        ),
    ]
