# Generated by Django 4.2.13 on 2024-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0060_studentmodulegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='points_goal_enabled',
            field=models.BooleanField(default=True, help_text='LABEL_POINTS_GOAL_ENABLED_HELP', verbose_name='LABEL_POINTS_GOAL_ENABLED'),
        ),
    ]
