# Generated by Django 4.2.11 on 2024-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0062_studentmodulegoal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodulegoal",
            name="personalized_points_goal",
            field=models.IntegerField(default=100),
        ),
    ]
