# Generated by Django 4.2.18 on 2025-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0062_studentmodulegoal_unique_student_module_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='group_work_allowed',
            field=models.BooleanField(default=False, verbose_name='LABEL_GROUP_WORK_ALLOWED'),
        ),
    ]
