# Generated by Django 4.2.18 on 2026-02-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0063_courseinstance_group_work_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinstance',
            options={
                'verbose_name': 'MODEL_NAME_COURSE_INSTANCE',
                'verbose_name_plural': 'MODEL_NAME_COURSE_INSTANCE_PLURAL',
                'permissions': (('view_current_teachers', 'Can view current teachers API endpoint'),),
            },
        ),
    ]
