# Generated by Django 5.2.14 on 2026-05-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0063_courseinstance_group_work_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinstance',
            options={'permissions': (('view_current_teachers', 'Can view current teachers API endpoint'),), 'verbose_name': 'MODEL_NAME_COURSE_INSTANCE', 'verbose_name_plural': 'MODEL_NAME_COURSE_INSTANCE_PLURAL'},
        ),
    ]
