# Generated by Django 4.2.11 on 2024-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0063_alter_studentmodulegoal_personalized_points_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodulegoal",
            name="personalized_points_goal",
            field=models.FloatField(default=100.0),
        ),
    ]
