# Generated by Django 5.2.15 on 2026-10-02 10:42

from django.db import migrations, models

def migrate_index_mode_to_results(apps, schema_editor):
    CourseInstance = apps.get_model('course', 'CourseInstance')
    CourseInstance.objects.filter(index_mode=2).update(index_mode=0)

class Migration(migrations.Migration):

    dependencies = [
        ('course', '0064_courseinstance_view_current_teachers_permission'),
    ]

    operations = [
        migrations.RunPython(
            migrate_index_mode_to_results,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='index_mode',
            field=models.IntegerField(choices=[(0, 'USER_RESULTS'), (1, 'TABLE_OF_CONTENTS'), (10, 'EXPERIMENTAL_SETUP')], default=0, help_text='COURSE_INSTANCE_INDEX_CONTENT_SELECTION_HELPTEXT', verbose_name='LABEL_INDEX_MODE'),
        ),
    ]
