# Generated by Django 3.2.4 on 2021-08-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210812_1536'),
        ('course', '0051_auto_20210812_1536'),
        ('exercise', '0039_auto_20210812_1536'),
        ('notification', '0004_auto_20190426_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'MODEL_NAME_NOTIFICATION', 'verbose_name_plural': 'MODEL_NAME_NOTIFICATION_PLURAL'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseinstance', verbose_name='LABEL_COURSE_INSTANCE'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.TextField(blank=True, verbose_name='LABEL_NOTIFICATION'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='userprofile.userprofile', verbose_name='LABEL_RECIPIENT'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='LABEL_SEEN'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='userprofile.userprofile', verbose_name='LABEL_SENDER'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='LABEL_SUBJECT'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exercise.submission', verbose_name='LABEL_SUBMISSION'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='LABEL_TIMESTAMP'),
        ),
    ]
