# Generated by Django 4.2.13 on 2024-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20210812_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='regrade_when_seen',
            field=models.BooleanField(default=False, verbose_name='LABEL_REGRADE_WHEN_SEEN'),
        ),
    ]
