# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0007_ltiservice_access_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiservice',
            name='access_settings',
            field=models.IntegerField(choices=[(0, 'Anonymous service, no API access'), (5, 'Public service, no API access'), (10, 'Public service, allow API access')], default=0, help_text="Select whether to pass pseudonymised user data to the LTI service.<br>Public services can also enable sharing the user's API token and course API URL in the LTI launch request. This grants the LTI tool API access with the user's privileges."),
        ),
    ]
