# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0008_auto_20180724_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkservice',
            name='menu_label',
            field=models.CharField(help_text='A default label to show in the course menu.', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_group_label',
            field=models.CharField(blank=True, help_text='Places menu item under a group label.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Label for the menu link (else service default).', max_length=255, null=True),
        ),
    ]
