# Generated by Django 2.2.12 on 2020-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0011_menuitem_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkservice',
            name='destination_region',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Destination is hosted internally. Link to internal privacy notice.'), (1, 'Destination is hosted in the same organization. Link to a privacy notice.'), (3, 'Destination is hosted in the European Economic Area. Link to a privacy notice.'), (5, 'Destination is hosted outside of the European Economic Area and used to be certified under the now invalid EU-US Privacy Shield. Link to an extended privacy notice.'), (6, 'Destination is hosted outside of the European Economic Area. Link to an extended privacy notice.')], default=6, help_text='The geographical area of the destination. Will display correct user notice.'),
        ),
    ]
