# Generated by Django 3.2.18 on 2023-06-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0016_alter_menuitem_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTI1p3Service',
            fields=[
                ('linkservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='external_services.linkservice')),
                ('login_url', models.CharField(max_length=256, verbose_name='Login initiation URL')),
                ('client_id', models.CharField(max_length=128, unique=True, verbose_name='Client ID')),
                ('deployment_id', models.CharField(max_length=128, verbose_name='Deployment ID')),
                ('jwks_url', models.CharField(max_length=256, verbose_name="JWKS URL for tool's public key")),
                ('share_name', models.BooleanField(default=False, verbose_name="Share launcher's name, email and student ID with the tool")),
            ],
            options={
                'verbose_name': 'MODEL_NAME_LTI1P3_SERVICE',
                'verbose_name_plural': 'MODEL_NAME_LTI1P3_SERVICE_PLURAL',
            },
            bases=('external_services.linkservice',),
        ),
    ]
