# Generated by Django 4.2.4 on 2024-02-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0017_lti1p3service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_url',
            field=models.CharField(blank=True, help_text='MENU_ITEM_MENU_URL_HELPTEXT', max_length=256, null=True, verbose_name='LABEL_MENU_URL'),
        ),
    ]
