# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0026_auto_20170428_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='templates',
            field=models.TextField(blank=True, help_text='List template files as protected URL addresses.'),
        ),
    ]
