# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0027_learningobject_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='service_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
