# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0028_auto_20180221_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='submission_in_effect',
            field=models.CharField(choices=[('L', 'Latest submission is in effect'), ('B', 'Best submission is in effect')], default='B', max_length=1),
        ),
    ]
