# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0030_auto_20180710_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='submission_in_effect',
            field=models.CharField(choices=[('L', 'Latest submission is in effect'), ('B', 'Best submission is in effect')], default='B', max_length=1),
        ),
    ]
