# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_auto_20180920_1838'),
        ('exercise', '0030_auto_20180710_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCollection',
            fields=[
                ('baseexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercise.BaseExercise')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.LearningObjectCategory')),
            ],
            bases=('exercise.baseexercise',),
        ),
    ]
