# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0034_auto_20190416_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='userprofile.UserProfile'),
        ),
    ]
