# Generated by Django 2.2.1 on 2019-10-24 10:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0035_auto_20190426_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='service_url',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='url',
            field=models.CharField(help_text='Input an URL identifier for this object.', max_length=512, validators=[django.core.validators.RegexValidator(message='URL keys may consist of alphanumeric characters, hyphen and period.', regex=re.compile('^\\w[\\w\\-\\.]*$'))]),
        ),
    ]
