# Generated by Django 2.2.13 on 2020-06-25 10:27

from django.db import migrations
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0036_auto_20191024_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='meta_data',
            field=lib.fields.JSONField(blank=True),
        ),
    ]
