# Generated by Django 3.2.4 on 2021-07-01 14:30

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0037_submission_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisewithattachment',
            name='files_to_submit',
            field=models.CharField(blank=True, help_text='EXERCISE_WITH_ATTACHMENT_FILES_TO_SUBMIT_HELPTEXT', max_length=200),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='audience',
            field=models.IntegerField(choices=[(0, 'AUDIENCE_COURSE_AUDIENCE'), (1, 'AUDIENCE_INTERNAL_USERS'), (2, 'AUDIENCE_EXTERNAL_USERS'), (3, 'AUDIENCE_REGISTERED_USERS')], default=0),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='description',
            field=models.TextField(blank=True, help_text='LEARNING_OBJECT_DESCRIPTION_HELPTEXT'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='model_answers',
            field=models.TextField(blank=True, help_text='LEARNING_OBJECT_MODEL_ANSWER_URLS_HELPTEXT'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='status',
            field=models.CharField(choices=[('enrollment', 'ENROLLMENT_QUESTIONS'), ('enrollment_ext', 'ENROLLMENT_QUESTIONS_FOR_EXTERNAL'), ('hidden', 'HIDDEN_FROM_NOT_COURSE_STAFF'), ('maintenance', 'STATUS_MAINTENANCE'), ('ready', 'STATUS_READY'), ('unlisted', 'STATUS_UNLISTED')], default='ready', max_length=32),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='templates',
            field=models.TextField(blank=True, help_text='LEARNING_OBJECT_TEMPLATE_URLS_HELPTEXT'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='url',
            field=models.CharField(help_text='LEARNING_OBJECT_URL_IDENTIFIER_HELPTEXT', max_length=512, validators=[django.core.validators.RegexValidator(message='URL_KEY_MAY_CONSIST_OF', regex=re.compile('^\\w[\\w\\-\\.]*$'))]),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='use_wide_column',
            field=models.BooleanField(default=False, help_text='LEARNING_OBJECT_WIDE_COLUMN_HELPTEXT'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='aplus_get_and_post',
            field=models.BooleanField(default=False, help_text='LTI_EXERCISE_APLUS_GET_AND_POST_HELPTEXT'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='context_id',
            field=models.CharField(blank=True, help_text='LTI_EXERCISE_CONTEXT_ID_HELPTEXT', max_length=128),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='open_in_iframe',
            field=models.BooleanField(default=False, help_text='LTI_EXERCISE_OPEN_IN_IFRAME_HELPTEXT'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='resource_link_id',
            field=models.CharField(blank=True, help_text='LTI_EXERCISE_RESOURCE_LINK_ID_HELPTEXT', max_length=128),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='resource_link_title',
            field=models.CharField(blank=True, help_text='LTI_EXERCISE_RESOURCE_LINK_TITLE_HELPTEXT', max_length=128),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('error', 'STATUS_ERROR'), ('initialized', 'STATUS_INITIALIZED'), ('ready', 'STATUS_READY'), ('rejected', 'STATUS_REJECTED'), ('unofficial', 'STATUS_UNOFFICIAL'), ('waiting', 'STATUS_WAITING')], default='initialized', max_length=32),
        ),
    ]
