# Generated by Django 3.2.4 on 2021-08-12 12:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exercise.exercise_models
import exercise.submission_models
import lib.fields
import lib.helpers
import re


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210812_1536'),
        ('course', '0051_auto_20210812_1536'),
        ('external_services', '0015_auto_20210812_1536'),
        ('exercise', '0038_auto_20210701_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseexercise',
            options={'verbose_name': 'MODEL_NAME_BASE_EXERCISE', 'verbose_name_plural': 'MODEL_NAME_BASE_EXERCISE_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'verbose_name': 'MODEL_NAME_COURSE_CHAPTER', 'verbose_name_plural': 'MODEL_NAME_COURSE_CHAPTER_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='exercisecollection',
            options={'verbose_name': 'MODEL_NAME_EXERCISE_COLLECTION', 'verbose_name_plural': 'MODEL_NAME_EXERCISE_COLLECTION_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='exercisewithattachment',
            options={'verbose_name': 'MODEL_NAME_EXERCISE_WITH_ATTACHMENT', 'verbose_name_plural': 'MODEL_NAME_EXERCISE_WITH_ATTACHMENT_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='learningobject',
            options={'ordering': ['course_module', 'order', 'id'], 'verbose_name': 'MODEL_NAME_LEARNING_OBJECT', 'verbose_name_plural': 'MODEL_NAME_LEARNING_OBJECT_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='learningobjectdisplay',
            options={'verbose_name': 'MODEL_NAME_LEARNING_OBJECT_DISPLAY', 'verbose_name_plural': 'MODEL_NAME_LEARNING_OBJECT_DISPLAY_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='ltiexercise',
            options={'verbose_name': 'MODEL_NAME_LTI_EXERCISE', 'verbose_name_plural': 'MODEL_NAME_LTI_EXERCISE_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='staticexercise',
            options={'verbose_name': 'MODEL_NAME_STATIC_EXERCISE', 'verbose_name_plural': 'MODEL_NAME_STATICE_EXERCISE_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-id'], 'verbose_name': 'MODEL_NAME_SUBMISSION', 'verbose_name_plural': 'MODEL_NAME_SUBMISSION_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='submittedfile',
            options={'verbose_name': 'MODEL_NAME_SUBMITTED_FILE', 'verbose_name_plural': 'MODEL_NAME_SUBMITTED_FILE_PLURAL'},
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='allow_assistant_grading',
            field=models.BooleanField(default=False, verbose_name='LABEL_ALLOW_ASSISTANT_GRADING'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='allow_assistant_viewing',
            field=models.BooleanField(default=True, verbose_name='LABEL_ALLOW_ASSISTANT_VIEWING'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='difficulty',
            field=models.CharField(blank=True, max_length=32, verbose_name='LABEL_DIFFICULTY'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='max_group_size',
            field=models.PositiveIntegerField(default=1, verbose_name='LABEL_MAX_GROUP_SIZE'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='max_points',
            field=models.PositiveIntegerField(default=100, verbose_name='LABEL_MAX_POINTS'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='max_submissions',
            field=models.PositiveIntegerField(default=10, verbose_name='LABEL_MAX_SUBMISSIONS'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='min_group_size',
            field=models.PositiveIntegerField(default=1, verbose_name='LABEL_MIN_GROUP_SIZE'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='points_to_pass',
            field=models.PositiveIntegerField(default=40, verbose_name='LABEL_POINTS_TO_PASS'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='generate_table_of_contents',
            field=models.BooleanField(default=False, verbose_name='LABEL_GENERATE_TOC'),
        ),
        migrations.AlterField(
            model_name='exercisecollection',
            name='target_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.learningobjectcategory', verbose_name='LABEL_TARGET_CATEGORY'),
        ),
        migrations.AlterField(
            model_name='exercisewithattachment',
            name='attachment',
            field=models.FileField(upload_to=exercise.exercise_models.build_upload_dir, verbose_name='LABEL_ATTACHMENT'),
        ),
        migrations.AlterField(
            model_name='exercisewithattachment',
            name='files_to_submit',
            field=models.CharField(blank=True, help_text='EXERCISE_WITH_ATTACHMENT_FILES_TO_SUBMIT_HELPTEXT', max_length=200, verbose_name='LABEL_FILES_TO_SUBMIT'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='audience',
            field=models.IntegerField(choices=[(0, 'AUDIENCE_COURSE_AUDIENCE'), (1, 'AUDIENCE_INTERNAL_USERS'), (2, 'AUDIENCE_EXTERNAL_USERS'), (3, 'AUDIENCE_REGISTERED_USERS')], default=0, verbose_name='LABEL_AUDIENCE'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objects', to='course.learningobjectcategory', verbose_name='LABEL_CATEGORY'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='content',
            field=models.TextField(blank=True, verbose_name='LABEL_CONTENT'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objects', to='course.coursemodule', verbose_name='LABEL_COURSE_MODULE'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='description',
            field=models.TextField(blank=True, help_text='LEARNING_OBJECT_DESCRIPTION_HELPTEXT', verbose_name='LABEL_DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='exercise_info',
            field=lib.fields.JSONField(blank=True, verbose_name='LABEL_EXERCISE_INFO'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='model_answers',
            field=models.TextField(blank=True, help_text='LEARNING_OBJECT_MODEL_ANSWER_URLS_HELPTEXT', verbose_name='LABEL_MODEL_ANSWERS'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='LABEL_NAME'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='order',
            field=models.IntegerField(default=1, verbose_name='LABEL_ORDER'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='exercise.learningobject', verbose_name='LABEL_PARENT'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='service_url',
            field=models.CharField(blank=True, max_length=4096, verbose_name='LABEL_SERVICE_URL'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='status',
            field=models.CharField(choices=[('enrollment', 'ENROLLMENT_QUESTIONS'), ('enrollment_ext', 'ENROLLMENT_QUESTIONS_FOR_EXTERNAL'), ('hidden', 'HIDDEN_FROM_NOT_COURSE_STAFF'), ('maintenance', 'STATUS_MAINTENANCE'), ('ready', 'STATUS_READY'), ('unlisted', 'STATUS_UNLISTED')], default='ready', max_length=32, verbose_name='LABEL_STATUS'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='templates',
            field=models.TextField(blank=True, help_text='LEARNING_OBJECT_TEMPLATE_URLS_HELPTEXT', verbose_name='LABEL_TEMPLATES'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='url',
            field=models.CharField(help_text='LEARNING_OBJECT_URL_IDENTIFIER_HELPTEXT', max_length=512, validators=[django.core.validators.RegexValidator(message='URL_KEY_MAY_CONSIST_OF', regex=re.compile('^\\w[\\w\\-\\.]*$'))], verbose_name='LABEL_URL'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='use_wide_column',
            field=models.BooleanField(default=False, help_text='LEARNING_OBJECT_WIDE_COLUMN_HELPTEXT', verbose_name='LABEL_USE_WIDE_COLUMN'),
        ),
        migrations.AlterField(
            model_name='learningobjectdisplay',
            name='learning_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.learningobject', verbose_name='LABEL_LEARNING_OBJECT'),
        ),
        migrations.AlterField(
            model_name='learningobjectdisplay',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='LABEL_PROFILE'),
        ),
        migrations.AlterField(
            model_name='learningobjectdisplay',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='LABEL_TIMESTAMP'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='aplus_get_and_post',
            field=models.BooleanField(default=False, help_text='LTI_EXERCISE_APLUS_GET_AND_POST_HELPTEXT', verbose_name='LABEL_APLUS_GET_AND_POST'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='context_id',
            field=models.CharField(blank=True, help_text='LTI_EXERCISE_CONTEXT_ID_HELPTEXT', max_length=128, verbose_name='LABEL_CONTEXT_ID'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='lti_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_services.ltiservice', verbose_name='LABEL_LTI_SERVICE'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='open_in_iframe',
            field=models.BooleanField(default=False, help_text='LTI_EXERCISE_OPEN_IN_IFRAME_HELPTEXT', verbose_name='LABEL_OPEN_IN_IFRAME'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='resource_link_id',
            field=models.CharField(blank=True, help_text='LTI_EXERCISE_RESOURCE_LINK_ID_HELPTEXT', max_length=128, verbose_name='LABEL_RESOURCE_LINK_ID'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='resource_link_title',
            field=models.CharField(blank=True, help_text='LTI_EXERCISE_RESOURCE_LINK_TITLE_HELPTEXT', max_length=128, verbose_name='LABEL_RESOURCE_LINK_TITLE'),
        ),
        migrations.AlterField(
            model_name='staticexercise',
            name='exercise_page_content',
            field=models.TextField(verbose_name='LABEL_EXERCISE_PAGE_CONTENT'),
        ),
        migrations.AlterField(
            model_name='staticexercise',
            name='submission_page_content',
            field=models.TextField(verbose_name='LABEL_SUBMISSION_PAGE_CONTENT'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assistant_feedback',
            field=models.TextField(blank=True, verbose_name='LABEL_STAFF_FEEDBACK'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='LABEL_FEEDBACK'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='LABEL_GRADE'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='userprofile.userprofile', verbose_name='LABEL_GRADER'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grading_data',
            field=lib.fields.JSONField(blank=True, verbose_name='LABEL_GRADING_DATA'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grading_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LABEL_GRADING_TIME'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hash',
            field=models.CharField(default=lib.helpers.get_random_string, max_length=32, verbose_name='LABEL_HASH'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='late_penalty_applied',
            field=lib.fields.PercentField(blank=True, null=True, verbose_name='LABEL_LATE_PENALTY_APPLIED'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='meta_data',
            field=lib.fields.JSONField(blank=True, verbose_name='LABEL_META_DATA'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='service_max_points',
            field=models.IntegerField(default=0, verbose_name='LABEL_SERVICE_MAX_POINTS'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='service_points',
            field=models.IntegerField(default=0, verbose_name='LABEL_SERVICE_POINTS'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('error', 'STATUS_ERROR'), ('initialized', 'STATUS_INITIALIZED'), ('ready', 'STATUS_READY'), ('rejected', 'STATUS_REJECTED'), ('unofficial', 'STATUS_UNOFFICIAL'), ('waiting', 'STATUS_WAITING')], default='initialized', max_length=32, verbose_name='LABEL_STATUS'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_data',
            field=lib.fields.JSONField(blank=True, verbose_name='LABEL_SUBMISSION_DATA'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='LABEL_SUBMISSION_TIME'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitters',
            field=models.ManyToManyField(related_name='submissions', to='userprofile.UserProfile', verbose_name='LABEL_SUBMITTERS'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='file_object',
            field=models.FileField(max_length=255, upload_to=exercise.submission_models.build_upload_dir, verbose_name='LABEL_FILE_OBJECT'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='param_name',
            field=models.CharField(max_length=128, verbose_name='LABEL_PARAM_NAME'),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exercise.submission', verbose_name='LABEL_SUBMISSION'),
        ),
    ]
