# Generated by Django 3.2.4 on 2021-07-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0039_auto_20210812_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='force_exercise_points',
            field=models.BooleanField(default=False, verbose_name='LABEL_FORCE_EXERCISE_POINTS'),
        ),
    ]
