# Generated by Django 3.2.4 on 2021-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0041_reveal_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='grading_mode',
            field=models.IntegerField(choices=[(1, 'GRADING_MODE_BEST'), (2, 'GRADING_MODE_LAST')], default=1, help_text='BASE_EXERCISE_GRADING_MODE_HELPTEXT', verbose_name='LABEL_GRADING_MODE'),
        ),
    ]
