# Generated by Django 3.2.4 on 2021-10-22 10:28

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210812_1536'),
        ('exercise', '0042_baseexercise_grading_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='LABEL_TIMESTAMP')),
                ('submission_data', lib.fields.JSONField(blank=True, verbose_name='LABEL_SUBMISSION_DATA')),
                ('active', models.BooleanField(default=True, verbose_name='LABEL_ACTIVE')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_drafts', to='exercise.baseexercise', verbose_name='LABEL_EXERCISE')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_drafts', to='userprofile.userprofile', verbose_name='LABEL_SUBMITTER')),
            ],
            options={
                'verbose_name': 'MODEL_NAME_SUBMISSION_DRAFT',
                'verbose_name_plural': 'MODEL_NAME_SUBMISSION_DRAFT_PLURAL',
                'unique_together': {('exercise', 'submitter')},
            },
        ),
    ]
