# Generated by Django 3.2.7 on 2022-01-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0043_submissiondraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='regrade_task',
            field=models.CharField(blank=True, max_length=128, verbose_name='LABEL_REGRADE_TASK'),
        ),
    ]
