# Generated by Django 3.2.7 on 2022-02-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0043_submissiondraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('regrade', 'REGRADE')], default='regrade', max_length=32, verbose_name='LABEL_TASK_TYPE')),
                ('task_id', models.CharField(max_length=128, verbose_name='LABEL_TASK_ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE')),
            ],
            options={
                'verbose_name': 'MODEL_NAME_EXERCISE_TASK',
                'verbose_name_plural': 'MODEL_NAME_EXERCISE_TASK_PLURAL',
            },
        ),
        migrations.AddConstraint(
            model_name='exercisetask',
            constraint=models.UniqueConstraint(fields=('exercise', 'task_type'), name='one_task_type_per_exercise'),
        ),
    ]
