# Generated by Django 3.2.4 on 2022-02-11 13:40

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0016_alter_menuitem_service'),
        ('exercise', '0044_auto_20220203_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseexercise',
            name='model_solutions_reveal_rule',
            field=lib.fields.DefaultOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercise.revealrule', verbose_name='LABEL_MODEL_SOLUTIONS_REVEAL_RULE'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='submission_feedback_reveal_rule',
            field=lib.fields.DefaultOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercise.revealrule', verbose_name='LABEL_SUBMISSION_FEEDBACK_REVEAL_RULE'),
        ),
        migrations.AlterField(
            model_name='exercisetask',
            name='exercise',
            field=lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='parent',
            field=lib.fields.DefaultForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='exercise.learningobject', verbose_name='LABEL_PARENT'),
        ),
        migrations.AlterField(
            model_name='learningobjectdisplay',
            name='learning_object',
            field=lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.learningobject', verbose_name='LABEL_LEARNING_OBJECT'),
        ),
        migrations.AlterField(
            model_name='ltiexercise',
            name='lti_service',
            field=lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_services.ltiservice', verbose_name='LABEL_LTI_SERVICE'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exercise',
            field=lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
        migrations.AlterField(
            model_name='submissiondraft',
            name='exercise',
            field=lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_drafts', to='exercise.baseexercise', verbose_name='LABEL_EXERCISE'),
        ),
    ]
