# Generated by Django 3.2.12 on 2022-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0046_pendingsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='defines_grade',
            field=models.BooleanField(default=False, verbose_name='Defines grade for this exercise'),
        ),
    ]
