# Generated by Django 4.2.4 on 2024-02-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0048_alter_revealrule_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='unofficial_submission_type',
            field=models.CharField(blank=True, choices=[('deadline_passed', 'DEADLINE_PASSED'), ('limit_exceeded', 'LIMIT_EXCEEDED')], default=None, max_length=64, null=True, verbose_name='LABEL_UNOFFICIAL_SUBMISSION_TYPE'),
        ),
    ]
