# Generated by Django 4.2.11 on 2024-04-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0059_submissiontag"),
        ("exercise", "0049_submission_unofficial_submission_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTagging",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_taggings",
                        to="exercise.submission",
                        verbose_name="LABEL_SUBMISSION",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_taggings",
                        to="course.submissiontag",
                        verbose_name="LABEL_SUBMISSION_TAG",
                    ),
                ),
            ],
            options={
                "ordering": ["tag"],
            },
        ),
    ]
