# Generated by Django 4.2.11 on 2024-06-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0050_submissiontagging"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseexercise",
            name="personalized_points_goal",
            field=models.PositiveIntegerField(
                default=100, verbose_name="LABEL_PERSONALIZED_POINTS_GOAL"
            ),
        ),
    ]
