# Generated by Django 5.2.15 on 2026-09-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0051_revealrule_show_zero_points_immediately'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningObjectDisplay',
        ),
    ]