# Generated by Django 4.2.26 on 2025-11-12 15:35

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210812_1536'),
        ('exercise', '0051_revealrule_show_zero_points_immediately'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseUserPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_count', models.PositiveIntegerField(default=0)),
                ('all_count', models.PositiveIntegerField(default=0)),
                ('official_best_grade', models.IntegerField(default=0)),
                ('official_last_grade', models.IntegerField(default=0)),
                ('all_best_grade', models.IntegerField(default=0)),
                ('all_last_grade', models.IntegerField(default=0)),
                ('forced_points', models.IntegerField(blank=True, null=True)),
                ('last_submission_id', models.IntegerField(blank=True, null=True)),
                ('best_submission_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', lib.fields.DefaultForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to='exercise.baseexercise', verbose_name='LABEL_EXERCISE')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_points', to='userprofile.userprofile', verbose_name='LABEL_SUBMITTER')),
            ],
            options={
                'verbose_name': 'Exercise user points',
                'verbose_name_plural': 'Exercise user points',
                'indexes': [models.Index(fields=['exercise', 'submitter'], name='exercise_ex_exercis_fa9c6c_idx'), models.Index(fields=['submitter'], name='exercise_ex_submitt_602a73_idx'), models.Index(fields=['exercise'], name='exercise_ex_exercis_f711f8_idx')],
                'unique_together': {('exercise', 'submitter')},
            },
        ),
    ]
