# Generated by Django 4.2.29 on 2026-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0051_revealrule_show_zero_points_immediately'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('error', 'STATUS_ERROR'), ('initialized', 'STATUS_INITIALIZED'), ('invalidated', 'STATUS_INVALIDATED'), ('ready', 'STATUS_READY'), ('rejected', 'STATUS_REJECTED'), ('unofficial', 'STATUS_UNOFFICIAL'), ('waiting', 'STATUS_WAITING')], default='initialized', max_length=32, verbose_name='LABEL_STATUS'),
        ),
    ]
