# Generated by Django 4.2.11 on 2024-06-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0051_baseexercise_personalized_points_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseexercise",
            name="personalized_points_goal",
        ),
    ]
