# Generated by Django 5.2.15 on 2026-10-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0052_alter_submission_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningObjectDisplay',
        ),
    ]
