# Generated by Django 2.2.3 on 2019-07-12 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0044_auto_20190415_1807'),
        ('userprofile', '0003_auto_20160728_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('start_time_actual', models.DateTimeField(default=django.utils.timezone.now)),
                ('may_leave_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.CharField(max_length=255)),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseInstance')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_started', models.DateTimeField(auto_now_add=True)),
                ('exam_finished', models.DateTimeField(default=django.utils.timezone.now)),
                ('system_identifier', models.CharField(max_length=255)),
                ('exam_version', models.CharField(max_length=255)),
                ('exam_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exammode.ExamSession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
    ]
