# Generated by Django 2.2.3 on 2019-07-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0003_auto_20160728_1139'),
        ('course', '0044_auto_20190415_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseInstance')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_started', models.DateTimeField(auto_now_add=True)),
                ('exam_version', models.CharField(max_length=255)),
                ('exam_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exammode.ExamSession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
    ]
