# Generated by Django 2.2.6 on 2019-10-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exammode', '0002_examsession_exam_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='may_leave_time',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='start_time_actual',
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseModule'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
