# Generated by Django 2.2.3 on 2020-01-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exammode', '0003_auto_20191029_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='can_start',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='duration',
        ),
    ]
