# Generated by Django 2.2.3 on 2020-01-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_auto_20200108_1511'),
        ('exammode', '0004_auto_20200108_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('exam_module', 'room')},
        ),
    ]
