# Generated by Django 2.2.3 on 2020-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exammode', '0005_auto_20200109_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('name', 'room')},
        ),
    ]
