# Generated by Django 2.2.3 on 2020-01-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exammode', '0006_auto_20200109_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='exam_module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.CourseModule'),
        ),
    ]
