# Generated by Django 2.2.3 on 2020-01-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exammode', '0007_auto_20200109_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='exam_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
