# Generated by Django 2.2.3 on 2020-01-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_active_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exammode.ExamAttempt'),
        ),
    ]
