# Generated by Django 2.2.18 on 2021-03-15 20:01

from django.db import migrations, models
from django.conf import settings
from userprofile.models import UserProfile

# Initialize organization based on logic earlier used to distinguish
# internal and external users: if user has student number, it is considered
# as internal and set according to LOCAL_ORGANIZATION setting, because
# earlier we have allowed for only home organization Haka authentication.
def set_organization(apps, schema_editor):
    Model = apps.get_model('userprofile', 'UserProfile')
    for profile in Model.objects.all():
        if bool(profile.student_id):
            profile.organization = settings.LOCAL_ORGANIZATION
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200721_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.RunPython(set_organization),
    ]
