# Generated by Django 4.2.11 on 2024-06-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_auto_20210812_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentModuleGoal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personalized_points_goal", models.IntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.userprofile",
                    ),
                ),
            ],
        ),
    ]
