# Generated by Django 4.2.11 on 2024-06-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_studentmodulegoal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentModuleGoal",
        ),
    ]
