# Generated by Django 3.2.4 on 2021-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20150527_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseplugin',
            name='container_pk',
            field=models.TextField(verbose_name='OBJECT_ID'),
        ),
        migrations.AlterField(
            model_name='basetab',
            name='container_pk',
            field=models.TextField(verbose_name='OBJECT_ID'),
        ),
        migrations.AlterField(
            model_name='basetab',
            name='label',
            field=models.CharField(help_text='TAB_LABEL_HELPTEXT', max_length=12),
        ),
        migrations.AlterField(
            model_name='basetab',
            name='title',
            field=models.CharField(help_text='TAB_TITLE_HELPTEXT', max_length=64),
        ),
    ]
