# Generated by Django 3.2.4 on 2021-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='consume_harder_points',
            field=models.BooleanField(default=False, help_text='HARDER_POINTS_CONSUMED_BY_EASIER_DIFFICULTY_REQUIREMENTS'),
        ),
    ]
