# Generated by Django 3.2.4 on 2021-08-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0051_auto_20210812_1536'),
        ('exercise', '0039_auto_20210812_1536'),
        ('threshold', '0002_alter_threshold_consume_harder_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodulerequirement',
            options={'verbose_name': 'MODEL_NAME_COURSE_MODULE_REQUIREMENT', 'verbose_name_plural': 'MODEL_NAME_COURSE_MODULE_REQUIREMENT_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='threshold',
            options={'verbose_name': 'MODEL_NAME_THRESHOLD', 'verbose_name_plural': 'MODEL_NAME_THRESHOLD_PLURAL'},
        ),
        migrations.AlterModelOptions(
            name='thresholdpoints',
            options={'ordering': ['threshold', 'order'], 'verbose_name': 'MODEL_NAME_THRESHOLD_POINTS', 'verbose_name_plural': 'MODEL_NAME_THRESHOLD_POINTS_PLURAL'},
        ),
        migrations.AlterField(
            model_name='coursemodulerequirement',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='course.coursemodule', verbose_name='LABEL_MODULE'),
        ),
        migrations.AlterField(
            model_name='coursemodulerequirement',
            name='negative',
            field=models.BooleanField(default=False, verbose_name='LABEL_NEGATIVE'),
        ),
        migrations.AlterField(
            model_name='coursemodulerequirement',
            name='threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threshold.threshold', verbose_name='LABEL_THRESHOLD'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='consume_harder_points',
            field=models.BooleanField(default=False, help_text='HARDER_POINTS_CONSUMED_BY_EASIER_DIFFICULTY_REQUIREMENTS', verbose_name='LABEL_CONSUME_HARDER_POINTS'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='course.courseinstance', verbose_name='LABEL_COURSE_INSTANCE'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='name',
            field=models.CharField(max_length=255, verbose_name='LABEL_NAME'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='passed_categories',
            field=models.ManyToManyField(blank=True, to='course.LearningObjectCategory', verbose_name='LABEL_PASSED_CATEGORIES'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='passed_exercises',
            field=models.ManyToManyField(blank=True, to='exercise.BaseExercise', verbose_name='LABEL_PASSED_EXERCISES'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='passed_modules',
            field=models.ManyToManyField(blank=True, to='course.CourseModule', verbose_name='LABEL_PASSED_MODULES'),
        ),
        migrations.AlterField(
            model_name='thresholdpoints',
            name='difficulty',
            field=models.CharField(blank=True, max_length=32, verbose_name='LABEL_DIFFICULTY'),
        ),
        migrations.AlterField(
            model_name='thresholdpoints',
            name='limit',
            field=models.PositiveIntegerField(verbose_name='LABEL_LIMIT'),
        ),
        migrations.AlterField(
            model_name='thresholdpoints',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='LABEL_ORDER'),
        ),
        migrations.AlterField(
            model_name='thresholdpoints',
            name='threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='threshold.threshold', verbose_name='LABEL_THRESHOLD'),
        ),
    ]
