from django.urls import re_path

from .urls import USER_URL_PREFIX, EDIT_URL_PREFIX
from . import views, staff_views

# These need to be listed before the exercise URL routings.
urlpatterns = [
    re_path(USER_URL_PREFIX + r'enroll/$',
        views.Enroll.as_view(),
        name='enroll'),
    # re_path(USER_URL_PREFIX + r'unenroll/$',
    #     views.Unenroll.as_view(),
    #     name='unenroll'),
    re_path(USER_URL_PREFIX + r'setlang',
        views.LanguageView.as_view(),
        name="set-enrollment-language"),
    re_path(USER_URL_PREFIX + r'export-calendar/$',
        views.CalendarExport.as_view(),
        name='export-calendar'),
    # re_path(USER_URL_PREFIX + r'filter-categories/$',
    #     views.FilterCategories.as_view(),
    #     name='filter-categories'),
    re_path(USER_URL_PREFIX + r'groups/$',
        views.GroupsView.as_view(),
        name="groups"),
    re_path(USER_URL_PREFIX + r'groups/select/$',
        views.GroupSelect.as_view(),
        name="group-select"),
    re_path(EDIT_URL_PREFIX + r'participants/$',
        staff_views.ParticipantsView.as_view(),
        name="participants"),
    re_path(EDIT_URL_PREFIX + r'enroll-students/$',
        staff_views.EnrollStudentsView.as_view(),
        name="enroll-students"),
    re_path(EDIT_URL_PREFIX + r'groups/$',
        staff_views.GroupsView.as_view(),
        name="groups-list"),
    re_path(EDIT_URL_PREFIX + r'groups/new/$',
        staff_views.GroupsEditView.as_view(),
        name="groups-add"),
    re_path(EDIT_URL_PREFIX + r'groups/(?P<group_id>\d+)/$',
        staff_views.GroupsEditView.as_view(),
        name="groups-edit"),
    re_path(EDIT_URL_PREFIX + r'groups/(?P<group_id>\d+)/delete/$',
        staff_views.GroupsDeleteView.as_view(),
        name="groups-delete"),
    re_path(EDIT_URL_PREFIX + r'all-exercise-submissions/$',
        views.AllSubmissionsView.as_view(),
        name="all-exercise-submissions"),
]
